export enum PathNames {
  HOME = 'HOME',
  NOT_FOUND = 'NOT_FOUND',

  /** Movies */
  MOVIE = 'MOVIE',
  MOVIES = 'MOVIES',
  /** Collections */
  MOVIES_NOW_PLAYING = 'MOVIES_NOW_PLAYING',
  MOVIES_POPULAR = 'MOVIES_POPULAR',
  MOVIES_TOP_RATED = 'MOVIES_TOP_RATED',
  MOVIES_UPCOMING = 'MOVIES_UPCOMING',

  /** Shows */
  SHOW = 'SHOW',
  SHOWS = 'SHOWS',
  /** Collections */
  SHOWS_POPULAR = 'SHOWS_POPULAR',
  SHOWS_TOP_RATED = 'SHOWS_TOP_RATED',
  SHOWS_AIRING_SOON = 'SHOWS_AIRING_SOON',
  SHOWS_AIRING_TODAY = 'SHOWS_AIRING_TODAY',
}
